'''
This file contains configuration parameters.
'''

ERROR_MSG = 'ERROR'
WINDOW_SIZE = 700
IMAGE_SIZE = 60
MENU_BTN_HEIGHT = 40
TREE_STAGE_HEIGHT = 60
TREE_PANEL_WIDTH = WINDOW_SIZE / 2
TREE_MOVE_BTN_WIDTH = 30
